create table
  public.job (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    status text not null,
    result jsonb null,
    options jsonb not null,
    started_at timestamp with time zone null,
    constraint job_pkey primary key (id)
  ) tablespace pg_default;
