name: Deploy simulate task

on:
  push:
    branches:
      - main
    paths:
      - 'tasks/simulate/**'
      - '.github/workflows/deploy.yml'

env:
  FUNCTION_NAME: simulate
  REGION: us-central1
  RUNTIME: python310

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4

      - id: Authenticate
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - id: Deploy
        name: Deploy Cloud Function
        uses: google-github-actions/deploy-cloud-functions@v2
        with:
          name: ${{ env.FUNCTION_NAME }}
          runtime: ${{ env.RUNTIME }}
          region: ${{ env.REGION }}
          source_dir: ./app/api/tasks/simulate
          entry_point: main
          env_vars: |
            SUPABASE_URL=${{ secrets.SUPABASE_URL }}
            SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
          memory_mb: 4096
          timeout: 300
          min_instances: 0
          max_instances: 2
          ingress_settings: 'ALLOW_ALL'
          
      - id: Test
        name: Test function
        run: |
          curl -X POST "${{ steps.deploy.outputs.url }}" \
            -H "Content-Type: application/json" \
            -d '{"job": 1}' \
            --fail
